title: MyAnimeStream
title_separator: "|"
description: A browser extension for Chrome and Firefox

author:
  name: "Simon Berger"
  bio: "Coffee consuming human being."
  location: "Switzerland"
  links:
    - label: "Homepage"
      icon: "fas fa-fw fa-link"
      url: "https://siku2.io"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/siku2"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/siku_2"

footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/MyAnimeStream"

logo: "/assets/img/logo128.png"

baseurl: /

include:
  - _pages

exclude:
  - README.md

remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: dirt
breadcrumbs: true
search: true

# Analytics
analytics:
  provider: "google-universal"
  google:
    tracking_id: "UA-131499018-1"
    anonymize_ip: true

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-include-cache
  - jekyll-paginate
  - jekyll-sitemap
  - jemoji


defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: false
      read_time: true

  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
